/* tslint:disable */
/* eslint-disable */
/**
 * Rawstack TS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0-alpha.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface ActionRequest {
    'id': string;
    'action': ActionRequestActionEnum;
    'status': ActionRequestStatusEnum;
}

export const ActionRequestActionEnum = {
    EmailVerification: 'EMAIL_VERIFICATION'
} as const;

export type ActionRequestActionEnum = typeof ActionRequestActionEnum[keyof typeof ActionRequestActionEnum];
export const ActionRequestStatusEnum = {
    Processing: 'PROCESSING',
    Completed: 'COMPLETED',
    Failed: 'FAILED'
} as const;

export type ActionRequestStatusEnum = typeof ActionRequestStatusEnum[keyof typeof ActionRequestStatusEnum];

export interface ActionRequestPostRequest {
    'token': string;
}
export interface ActionRequestResponse {
    'item': ActionRequest;
}
export interface AuthAction {
    'action': AuthActionActionEnum;
}

export const AuthActionActionEnum = {
    CheckEmail: 'CHECK_EMAIL'
} as const;

export type AuthActionActionEnum = typeof AuthActionActionEnum[keyof typeof AuthActionActionEnum];

export interface AuthToken {
    /**
     * The access token
     */
    'accessToken': string;
    /**
     * The refresh token
     */
    'refreshToken': string;
    /**
     * The date and time when the token expires
     */
    'expiresAt': string;
    /**
     * Time to live in seconds
     */
    'ttlSeconds': number;
}
export interface AuthTokenPostRequest {
    'email': string;
    'password'?: string;
    'refreshToken'?: string;
    /**
     * Optional role to assign during token creation (only ADMIN role is supported)
     */
    'role'?: AuthTokenPostRequestRoleEnum;
    /**
     * If true, invalidates all existing tokens for this user before creating a new one
     */
    'invalidateTokens'?: boolean;
}

export const AuthTokenPostRequestRoleEnum = {
    Admin: 'ADMIN'
} as const;

export type AuthTokenPostRequestRoleEnum = typeof AuthTokenPostRequestRoleEnum[keyof typeof AuthTokenPostRequestRoleEnum];

export interface AuthTokenResponse {
    'item': AuthTokenResponseItem;
}
/**
 * @type AuthTokenResponseItem
 */
export type AuthTokenResponseItem = AuthAction | AuthToken;

export interface ConflictError {
    'message'?: string;
}
export interface ModelError {
    'message': string;
    'error': Array<string>;
    'statusCode': number;
}
export interface Pagination {
    'page': number;
    'perPage': number;
    'totalItems': number;
}
export interface UpdateUserRequest {
    'email'?: string;
    'password'?: string;
    /**
     * Array of roles to assign to the user (ADMIN or VERIFIED_USER)
     */
    'roles'?: Array<UpdateUserRequestRolesEnum>;
}

export const UpdateUserRequestRolesEnum = {
    Admin: 'ADMIN',
    VerifiedUser: 'VERIFIED_USER'
} as const;

export type UpdateUserRequestRolesEnum = typeof UpdateUserRequestRolesEnum[keyof typeof UpdateUserRequestRolesEnum];

export interface User {
    'id': string;
    'roles': Array<UserRolesEnum>;
    'email': string;
    'unverifiedEmail'?: string;
    'createdAt': string;
    'updatedAt': string;
}

export const UserRolesEnum = {
    Admin: 'ADMIN',
    VerifiedUser: 'VERIFIED_USER'
} as const;

export type UserRolesEnum = typeof UserRolesEnum[keyof typeof UserRolesEnum];

export interface UserListResponse {
    'items': Array<User>;
    'meta': UserListResponseMeta;
}
export interface UserListResponseMeta {
    'pagination': Pagination;
}
export interface UserPostRequest {
    'email': string;
    /**
     * Optional password. If not provided, admin users can create the user with a random password.
     */
    'password'?: string;
}
export interface UserResponse {
    'item': User;
}

/**
 * AuthenticationApi - axios parameter creator
 */
export const AuthenticationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Creates an Auth Action Request
         * @param {ActionRequestPostRequest} actionRequestPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createActionRequest: async (actionRequestPostRequest: ActionRequestPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'actionRequestPostRequest' is not null or undefined
            assertParamExists('createActionRequest', 'actionRequestPostRequest', actionRequestPostRequest)
            const localVarPath = `/auth/action-requests`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(actionRequestPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Creates an Auth Token
         * @param {AuthTokenPostRequest} authTokenPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createToken: async (authTokenPostRequest: AuthTokenPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authTokenPostRequest' is not null or undefined
            assertParamExists('createToken', 'authTokenPostRequest', authTokenPostRequest)
            const localVarPath = `/auth/tokens`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(authTokenPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Returns an Auth Action Request
         * @param {string} requestId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getActionRequest: async (requestId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'requestId' is not null or undefined
            assertParamExists('getActionRequest', 'requestId', requestId)
            const localVarPath = `/auth/action-requests/{requestId}`
                .replace(`{${"requestId"}}`, encodeURIComponent(String(requestId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthenticationApi - functional programming interface
 */
export const AuthenticationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthenticationApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Creates an Auth Action Request
         * @param {ActionRequestPostRequest} actionRequestPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createActionRequest(actionRequestPostRequest: ActionRequestPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ActionRequestResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createActionRequest(actionRequestPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.createActionRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Creates an Auth Token
         * @param {AuthTokenPostRequest} authTokenPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createToken(authTokenPostRequest: AuthTokenPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthTokenResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createToken(authTokenPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.createToken']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Returns an Auth Action Request
         * @param {string} requestId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getActionRequest(requestId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ActionRequestResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getActionRequest(requestId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.getActionRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthenticationApi - factory interface
 */
export const AuthenticationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthenticationApiFp(configuration)
    return {
        /**
         * 
         * @summary Creates an Auth Action Request
         * @param {ActionRequestPostRequest} actionRequestPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createActionRequest(actionRequestPostRequest: ActionRequestPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ActionRequestResponse> {
            return localVarFp.createActionRequest(actionRequestPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Creates an Auth Token
         * @param {AuthTokenPostRequest} authTokenPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createToken(authTokenPostRequest: AuthTokenPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<AuthTokenResponse> {
            return localVarFp.createToken(authTokenPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Returns an Auth Action Request
         * @param {string} requestId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getActionRequest(requestId: string, options?: RawAxiosRequestConfig): AxiosPromise<ActionRequestResponse> {
            return localVarFp.getActionRequest(requestId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthenticationApi - object-oriented interface
 */
export class AuthenticationApi extends BaseAPI {
    /**
     * 
     * @summary Creates an Auth Action Request
     * @param {ActionRequestPostRequest} actionRequestPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createActionRequest(actionRequestPostRequest: ActionRequestPostRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).createActionRequest(actionRequestPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Creates an Auth Token
     * @param {AuthTokenPostRequest} authTokenPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createToken(authTokenPostRequest: AuthTokenPostRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).createToken(authTokenPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Returns an Auth Action Request
     * @param {string} requestId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getActionRequest(requestId: string, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).getActionRequest(requestId, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UserApi - axios parameter creator
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Creates a new User
         * @param {UserPostRequest} userPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUser: async (userPostRequest: UserPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userPostRequest' is not null or undefined
            assertParamExists('createUser', 'userPostRequest', userPostRequest)
            const localVarPath = `/user/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerToken required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Deletes a user
         * @summary Deletes a user
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUser: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteUser', 'id', id)
            const localVarPath = `/user/users/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerToken required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the current user
         * @summary Returns the current user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentUser: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/user/users/current`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerToken required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a user
         * @summary Returns a user
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUser: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getUser', 'id', id)
            const localVarPath = `/user/users/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerToken required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a list of Users to admin users only
         * @summary Returns a list of Users
         * @param {number} [page] 
         * @param {number} [perPage] 
         * @param {string} [q] 
         * @param {ListUsersRoleEnum} [role] Filter users by role
         * @param {ListUsersOrderByEnum} [orderBy] Field to order results by
         * @param {ListUsersOrderEnum} [order] Sort order (ascending or descending)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listUsers: async (page?: number, perPage?: number, q?: string, role?: ListUsersRoleEnum, orderBy?: ListUsersOrderByEnum, order?: ListUsersOrderEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/user/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerToken required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['perPage'] = perPage;
            }

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }

            if (role !== undefined) {
                localVarQueryParameter['role'] = role;
            }

            if (orderBy !== undefined) {
                localVarQueryParameter['orderBy'] = orderBy;
            }

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates a user
         * @summary Updates a user
         * @param {string} id 
         * @param {UpdateUserRequest} updateUserRequest Request for updating a User
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUser: async (id: string, updateUserRequest: UpdateUserRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateUser', 'id', id)
            // verify required parameter 'updateUserRequest' is not null or undefined
            assertParamExists('updateUser', 'updateUserRequest', updateUserRequest)
            const localVarPath = `/user/users/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerToken required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateUserRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Creates a new User
         * @param {UserPostRequest} userPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createUser(userPostRequest: UserPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createUser(userPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.createUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Deletes a user
         * @summary Deletes a user
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteUser(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteUser(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.deleteUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns the current user
         * @summary Returns the current user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCurrentUser(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCurrentUser(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getCurrentUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns a user
         * @summary Returns a user
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUser(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUser(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns a list of Users to admin users only
         * @summary Returns a list of Users
         * @param {number} [page] 
         * @param {number} [perPage] 
         * @param {string} [q] 
         * @param {ListUsersRoleEnum} [role] Filter users by role
         * @param {ListUsersOrderByEnum} [orderBy] Field to order results by
         * @param {ListUsersOrderEnum} [order] Sort order (ascending or descending)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listUsers(page?: number, perPage?: number, q?: string, role?: ListUsersRoleEnum, orderBy?: ListUsersOrderByEnum, order?: ListUsersOrderEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listUsers(page, perPage, q, role, orderBy, order, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.listUsers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Updates a user
         * @summary Updates a user
         * @param {string} id 
         * @param {UpdateUserRequest} updateUserRequest Request for updating a User
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateUser(id: string, updateUserRequest: UpdateUserRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateUser(id, updateUserRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.updateUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * 
         * @summary Creates a new User
         * @param {UserPostRequest} userPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUser(userPostRequest: UserPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<UserResponse> {
            return localVarFp.createUser(userPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Deletes a user
         * @summary Deletes a user
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUser(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteUser(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the current user
         * @summary Returns the current user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentUser(options?: RawAxiosRequestConfig): AxiosPromise<UserResponse> {
            return localVarFp.getCurrentUser(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a user
         * @summary Returns a user
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUser(id: string, options?: RawAxiosRequestConfig): AxiosPromise<UserResponse> {
            return localVarFp.getUser(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a list of Users to admin users only
         * @summary Returns a list of Users
         * @param {number} [page] 
         * @param {number} [perPage] 
         * @param {string} [q] 
         * @param {ListUsersRoleEnum} [role] Filter users by role
         * @param {ListUsersOrderByEnum} [orderBy] Field to order results by
         * @param {ListUsersOrderEnum} [order] Sort order (ascending or descending)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listUsers(page?: number, perPage?: number, q?: string, role?: ListUsersRoleEnum, orderBy?: ListUsersOrderByEnum, order?: ListUsersOrderEnum, options?: RawAxiosRequestConfig): AxiosPromise<UserListResponse> {
            return localVarFp.listUsers(page, perPage, q, role, orderBy, order, options).then((request) => request(axios, basePath));
        },
        /**
         * Updates a user
         * @summary Updates a user
         * @param {string} id 
         * @param {UpdateUserRequest} updateUserRequest Request for updating a User
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUser(id: string, updateUserRequest: UpdateUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<UserResponse> {
            return localVarFp.updateUser(id, updateUserRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 */
export class UserApi extends BaseAPI {
    /**
     * 
     * @summary Creates a new User
     * @param {UserPostRequest} userPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createUser(userPostRequest: UserPostRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).createUser(userPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Deletes a user
     * @summary Deletes a user
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteUser(id: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).deleteUser(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the current user
     * @summary Returns the current user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCurrentUser(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getCurrentUser(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a user
     * @summary Returns a user
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getUser(id: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getUser(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a list of Users to admin users only
     * @summary Returns a list of Users
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {string} [q] 
     * @param {ListUsersRoleEnum} [role] Filter users by role
     * @param {ListUsersOrderByEnum} [orderBy] Field to order results by
     * @param {ListUsersOrderEnum} [order] Sort order (ascending or descending)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listUsers(page?: number, perPage?: number, q?: string, role?: ListUsersRoleEnum, orderBy?: ListUsersOrderByEnum, order?: ListUsersOrderEnum, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).listUsers(page, perPage, q, role, orderBy, order, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates a user
     * @summary Updates a user
     * @param {string} id 
     * @param {UpdateUserRequest} updateUserRequest Request for updating a User
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateUser(id: string, updateUserRequest: UpdateUserRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).updateUser(id, updateUserRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

export const ListUsersRoleEnum = {
    Admin: 'ADMIN',
    VerifiedUser: 'VERIFIED_USER'
} as const;
export type ListUsersRoleEnum = typeof ListUsersRoleEnum[keyof typeof ListUsersRoleEnum];
export const ListUsersOrderByEnum = {
    CreatedAt: 'createdAt',
    UpdatedAt: 'updatedAt',
    Email: 'email'
} as const;
export type ListUsersOrderByEnum = typeof ListUsersOrderByEnum[keyof typeof ListUsersOrderByEnum];
export const ListUsersOrderEnum = {
    Desc: 'DESC',
    Asc: 'ASC'
} as const;
export type ListUsersOrderEnum = typeof ListUsersOrderEnum[keyof typeof ListUsersOrderEnum];


